services:
  db:
    image: postgres:latest
    container_name: neosave_db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Kgar3@#!"
      POSTGRES_DB: "NeoSave"
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - sqlvolume:/var/lib/postgresql/data
   

 
  api:
    build:
      context: .
      dockerfile: NeoSave.API/Dockerfile
    ports:
      - "8088:80"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__DefaultConnection: "Server=db;Port=5432;Database=NeoSave;User ID=postgres;Password=Kgar3@#!;Pooling=true;"

volumes:
  sqlvolume:
