
services:
  db:
    image: postgres:17-alpine # Use lighter Alpine version
    container_name: neosave_db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Kgar3@#!"
      POSTGRES_DB: "NeoSave"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - sqlvolume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
      # Enable BuildKit features
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "8088:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__DefaultConnection: "Server=db;Port=5432;Database=NeoSave;User ID=postgres;Password=Kgar3@#!;Pooling=true;"
    restart: always
    

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      # Enable BuildKit caching
      cache_from:
        - node:20-alpine
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - api
    restart: always
    

volumes:
  sqlvolume:
