# Docker Compose for NeoSave
# Use .env and .env.local for secrets and URLs
# Example .env:
# POSTGRES_USER=postgres
# POSTGRES_PASSWORD=yourpassword
# POSTGRES_DB=NeoSave
# NEXT_PUBLIC_API_BASE_URL=http://api/api
# ASPNETCORE_ENVIRONMENT=Production
#
# To override for local dev, use .env.local
#
# Do not hardcode secrets or dev URLs below!
services:
  db:
    image: postgres:17-alpine
    container_name: neosave_db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Kgar3@#!"
      POSTGRES_DB: "NeoSave"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - sqlvolume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: NeoSave.API/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "8088:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__DefaultConnection: "Server=db;Port=5432;Database=NeoSave;User ID=postgres;Password=Kgar3@#!;Pooling=true;"
      Jwt__Key: "your-very-secret-key-please-change-this-in-production-1234567890"
      Jwt__Issuer: "NeoSaveAPI"
      Jwt__Audience: "NeoSaveFrontend"
    restart: always

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE_URL: http://api/api
    depends_on:
      - api
    restart: always

volumes:
  sqlvolume:
