services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: neosave_sql
    environment:
      SA_PASSWORD: "Kgar3@#!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: NeoSave.API/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=db;Database=NeoSave;User=sa;Password=Kgar3@#!;

volumes:
  sqlvolume:
