# Build stage
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

# Copy project file and restore dependencies
COPY NeoSave.API.csproj ./
RUN dotnet restore "NeoSave.API.csproj"

# Copy everything else and build
COPY . ./
RUN dotnet publish "NeoSave.API.csproj" -c Release -o out

# Runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out .

EXPOSE 80
ENTRYPOINT ["dotnet", "NeoSave.API.dll"]
